remote_theme: me/panthera-jekyll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Shailesh B Nair
subtitle: Senior Engineering Manager (Data Science Projects)

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Shailesh B Nair"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/shaileshbnair
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/sbnair
    icon: fab fa-github-square



    
